### ISSUE TITLE
the shader strongly degrades the image on android

### ISSUE THREAD

**Issue by splitter77** [otdavies/UnityChromakey#3]
the shader strongly degrades the image on android, while on ios it works extremely well.

[exemple](https://photos.app.goo.gl/xtKdGJ7WNZ3X8u7r7)

**Comment by otdavies** [comment]
Hmm, odd. I'll take a look at this. Could be something to do with texture compression. Does the image look as pixelated without the shader on it? (Just double checking it isn't the image itself).

I haven't optimized the shader for Android, so I haven't checked how it preforms.

**Comment by splitter77** [comment]
no the image appears non-pixelated without the shader, what is strange is that there are android phone models where there is no pixelation.

**Comment by otdavies** [comment]
After some testing: I've concluded that if the image is compressed (must be on android) it's green values will be compressed in a way to cause "blocky" looking edges due to the compression algorithm. The shader itself wouldn't cause this and I cannot reproduce it without compressed video. I am closing this as it is outside the scope of this repository.
